ignore = ['development finance corporation ltd',
          'estates and constructions ltd', 
          'finance corporation ltd',
          'marketing system ltd',
          'and constructions ltd',
          'and entertainments ltd', 
          'and plantations ltd',
          'and traders pvt ltd',
          'and food beverage ltd',
          'food beverage ltd',
          'traders pvt ltd',
          'development ltd',
          'corporation ltd',
          'automobiles ltd', 
          'system ltd', 
          'plantations ltd',
          'constructions ltd', 
          'entertainments ltd', 
          'airlines ltd',
          'lines ltd',
          'communications ltd',
          'company pvt. ltd.', 
          'india ltd', 
          'and travels ltd.', 
          'pvt. ltd.', 
          'pvt ltd', 
          'pvt.ltd.', 
          'ltd.', 
          'ltd', 
          'communication',
          'communications']  # 'cement private limited',

replacing = {'&': ' and ',
           'ltd': ' ltd ',
           'pvt': ' pvt ',
           ' pv ': ' pvt ',
           'properties': ' properties ',
           ' prop ': ' properties ',
           'limited': ' ltd ',
           'lim': ' ltd ',
           'lt': ' ltd ',
           'const': ' constructions ',
           ' cons ': ' constructions ',
           'entp': ' enterprise ',
           'engg': ' engineering ',
           'trdg': ' trading ',
           'commn': ' communication ',
           'mkting': ' marketing ',
           'mkt ': ' market ',
           'hitech': ' hi tech ',
           'tele media': ' telemedia ',
           ' pub ': ' publications ',
           'india': ' india ',
           'private': ' pvt ',
           'pratidin': ' pratidin ',
           ' .com ': '.com ',
           ' pro ': ' productions ',
           'comm ': ' communication ',
           'commn ': ' communication ',
           ' i ': ' india ',
           'hotels': ' hotels ',
           'estates': ' estates ',
           'valley': ' valley ',
           ' kr ': ' kumar ',
           ' vly ': ' valley ',
           ' est ': ' estates '}
