ignore = ['development ltd',
          'development finance corporation ltd',
          'finance corporation ltd',
          'corporation ltd',
          'marketing system ltd',
          'private ltd', 
          'automobiles ltd', 
          'system ltd', 
          'estates and constructions ltd', 
          'and constructions ltd', 
          'constructions ltd', 
          'and entertainments ltd', 
          'entertainments ltd', 
          'airlines ltd',
          'lines ltd',
          'communications ltd',
          'company pvt. ltd.', 
          'india ltd', 
          'and travels ltd.', 
          'pvt. ltd.', 
          'pvt ltd', 
          'pvt.ltd.', 
          'ltd.', 
          'ltd', 
          'communication' ]  # 'cement private limited',

replace = {'&': ' and ',
           'ltd': ' ltd ',
           'pvt': ' pvt ',
           ' pv ': ' pvt ',
           'properties': ' properties ',
           ' prop ': ' properties ',
           'limited': ' ltd ',
           'lim': ' ltd ',
           'lt': ' ltd ',
           'const': ' constructions ',
           ' cons ': ' constructions ',
           'entp': ' enterprise ',
           'engg': ' engineering ',
           'trdg': ' trading ',
           'commn': ' communication ',
           'mkting': ' marketing ',
           'mkt ': ' market ',
           'hitech': ' hi tech ',
           'tele media': ' telemedia ',
           ' pub ': ' publications ',
           'india': ' india ',
           'private': ' pvt ',
           'pratidin': ' pratidin ',
           ' .com ': '.com ',
           ' pro ': ' productions ',
           'comm ': ' communication ',
           'commn ': ' communication ',
           ' i ': ' india ',
           'hotels': ' hotels ',
           'estates': ' estates ',
           'valley': ' valley ',
           'kr': ' kumar '}
