replacing_entities = {'ltd': ' ltd ',
                      'pvt': ' pvt ',
                      ' pv ': ' pvt ',
                      ' pltd ': ' pvt limited',
                      'properties': ' properties ',
                      ' prop ': ' properties ',
                      'limited': ' ltd ',
                      ' lim ': ' ltd ',
                      ' lt ': ' ltd ',
                      'const ': ' constructions ',
                      ' cons ': ' constructions ',
                      'entp': ' enterprise ',
                      ' enterp ': ' enterprises ',
                      ' entert ': ' entertainment ',
                      'engg': ' engineering ',
                      'trdg': ' trading ',
                      'commn': ' communication ',
                      'mkting': ' marketing ',
                      'mkt ': ' market ',
                      'hitech ': ' hi tech ',
                      'autotech ': ' auto tech ',
                      'infotech ': ' info tech ',
                      'fasttech ': ' fast tech ',
                      'microtech ': ' micro tech ',
                      'tele media': ' telemedia ',
                      ' pub ': ' publications ',
                      'indian': ' indian ',
                      'india ': ' india ',
                      ' i ': ' india ',
                      'private': ' pvt ',
                      'pratidin': ' pratidin ',
                      ' .com ': '.com ',
                      ' pro ': ' productions ',
                      'commn ': ' communication ',
                      'hotels': ' hotels ',
                      'estates': ' estates ',
                      ' est ': ' estates ',
                      'corpn': 'corporarion',
                      'mfg': ' manufacturing '}

replacing_misc = {'a/c': ' ac ',
                  'trf': ' trf ',
                  'm/s ': ' 1 ',
                  ' vly ': ' valley ',
                  '&': ' and ',
                  'valley': ' valley ',
                  }

replacing_indi = {' kr ': ' kumar '
                  }
