# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'extras/main_window.ui'
#
# Created: Wed Jul 23 05:42:06 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(755, 563)
        MainWindow.setMaximumSize(QtCore.QSize(766, 586))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.elapsed_time = QtGui.QLabel(self.centralwidget)
        self.elapsed_time.setObjectName(_fromUtf8("elapsed_time"))
        self.horizontalLayout_6.addWidget(self.elapsed_time)
        self.timeEdit = QtGui.QTimeEdit(self.centralwidget)
        self.timeEdit.setObjectName(_fromUtf8("timeEdit"))
        self.horizontalLayout_6.addWidget(self.timeEdit)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.start_button = QtGui.QPushButton(self.centralwidget)
        self.start_button.setObjectName(_fromUtf8("start_button"))
        self.horizontalLayout_6.addWidget(self.start_button)
        self.cancel_button = QtGui.QPushButton(self.centralwidget)
        self.cancel_button.setObjectName(_fromUtf8("cancel_button"))
        self.horizontalLayout_6.addWidget(self.cancel_button)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.gridLayout.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.summary = QtGui.QWidget()
        self.summary.setObjectName(_fromUtf8("summary"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.summary)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lineEdit = QtGui.QLineEdit(self.summary)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit)
        self.label_4 = QtGui.QLabel(self.summary)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_2 = QtGui.QLineEdit(self.summary)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_6 = QtGui.QLabel(self.summary)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_3 = QtGui.QLineEdit(self.summary)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_2 = QtGui.QLabel(self.summary)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_3.addLayout(self.formLayout)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.lineEdit_4 = QtGui.QLineEdit(self.summary)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_5 = QtGui.QLabel(self.summary)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_5 = QtGui.QLineEdit(self.summary)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_5)
        self.label_7 = QtGui.QLabel(self.summary)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_6 = QtGui.QLineEdit(self.summary)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_6)
        self.label_3 = QtGui.QLabel(self.summary)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_3.addLayout(self.formLayout_2)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.summary, _fromUtf8(""))
        self.amounts = QtGui.QWidget()
        self.amounts.setObjectName(_fromUtf8("amounts"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.amounts)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.scrollArea = QtGui.QScrollArea(self.amounts)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 335, 564))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_8 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_7 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_7)
        self.label_10 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_10)
        self.lineEdit_13 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_13)
        self.label_12 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_12)
        self.lineEdit_12 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_12)
        self.label_13 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_13)
        self.lineEdit_11 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_11)
        self.label_11 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_11)
        self.lineEdit_10 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdit_10)
        self.label_14 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_14)
        self.lineEdit_9 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineEdit_9)
        self.label_17 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_17)
        self.lineEdit_18 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_18.setReadOnly(True)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.FieldRole, self.lineEdit_18)
        self.label_16 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_16)
        self.lineEdit_17 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.FieldRole, self.lineEdit_17)
        self.label_15 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_3.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_15)
        self.lineEdit_16 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.formLayout_3.setWidget(9, QtGui.QFormLayout.FieldRole, self.lineEdit_16)
        self.label_18 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_3.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_18)
        self.lineEdit_15 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.formLayout_3.setWidget(10, QtGui.QFormLayout.FieldRole, self.lineEdit_15)
        self.label_19 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_3.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_19)
        self.lineEdit_8 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.formLayout_3.setWidget(11, QtGui.QFormLayout.FieldRole, self.lineEdit_8)
        self.label_20 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_3.setWidget(12, QtGui.QFormLayout.LabelRole, self.label_20)
        self.lineEdit_14 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.formLayout_3.setWidget(12, QtGui.QFormLayout.FieldRole, self.lineEdit_14)
        self.label_23 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.formLayout_3.setWidget(13, QtGui.QFormLayout.LabelRole, self.label_23)
        self.lineEdit_22 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_22.setReadOnly(True)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.formLayout_3.setWidget(13, QtGui.QFormLayout.FieldRole, self.lineEdit_22)
        self.label_22 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.formLayout_3.setWidget(14, QtGui.QFormLayout.LabelRole, self.label_22)
        self.lineEdit_21 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_21.setReadOnly(True)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.formLayout_3.setWidget(14, QtGui.QFormLayout.FieldRole, self.lineEdit_21)
        self.label_21 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout_3.setWidget(15, QtGui.QFormLayout.LabelRole, self.label_21)
        self.lineEdit_20 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_20.setReadOnly(True)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.formLayout_3.setWidget(15, QtGui.QFormLayout.FieldRole, self.lineEdit_20)
        self.label_24 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.formLayout_3.setWidget(16, QtGui.QFormLayout.LabelRole, self.label_24)
        self.lineEdit_19 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_19.setReadOnly(True)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.formLayout_3.setWidget(16, QtGui.QFormLayout.FieldRole, self.lineEdit_19)
        self.label_28 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.formLayout_3.setWidget(17, QtGui.QFormLayout.LabelRole, self.label_28)
        self.lineEdit_23 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_23.setReadOnly(True)
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.formLayout_3.setWidget(17, QtGui.QFormLayout.FieldRole, self.lineEdit_23)
        self.verticalLayout.addLayout(self.formLayout_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.addWidget(self.scrollArea)
        self.scrollArea_2 = QtGui.QScrollArea(self.amounts)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 334, 564))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_25 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_25)
        self.label_26 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_26)
        self.lineEdit_24 = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_24.setReadOnly(True)
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_24)
        self.label_27 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_27)
        self.lineEdit_25 = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_25.setReadOnly(True)
        self.lineEdit_25.setObjectName(_fromUtf8("lineEdit_25"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_25)
        self.label_29 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_29)
        self.lineEdit_26 = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_26.setReadOnly(True)
        self.lineEdit_26.setObjectName(_fromUtf8("lineEdit_26"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_26)
        self.label_30 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_30)
        self.lineEdit_27 = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_27.setReadOnly(True)
        self.lineEdit_27.setObjectName(_fromUtf8("lineEdit_27"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_27)
        self.label_31 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_31)
        self.lineEdit_28 = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_28.setReadOnly(True)
        self.lineEdit_28.setObjectName(_fromUtf8("lineEdit_28"))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdit_28)
        self.label_32 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.formLayout_4.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_32)
        self.lineEdit_29 = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_29.setReadOnly(True)
        self.lineEdit_29.setObjectName(_fromUtf8("lineEdit_29"))
        self.formLayout_4.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineEdit_29)
        self.label_33 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.formLayout_4.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_33)
        self.lineEdit_30 = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_30.setReadOnly(True)
        self.lineEdit_30.setObjectName(_fromUtf8("lineEdit_30"))
        self.formLayout_4.setWidget(7, QtGui.QFormLayout.FieldRole, self.lineEdit_30)
        self.label_34 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.formLayout_4.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_34)
        self.lineEdit_31 = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_31.setReadOnly(True)
        self.lineEdit_31.setObjectName(_fromUtf8("lineEdit_31"))
        self.formLayout_4.setWidget(8, QtGui.QFormLayout.FieldRole, self.lineEdit_31)
        self.label_35 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.formLayout_4.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_35)
        self.lineEdit_32 = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_32.setReadOnly(True)
        self.lineEdit_32.setObjectName(_fromUtf8("lineEdit_32"))
        self.formLayout_4.setWidget(9, QtGui.QFormLayout.FieldRole, self.lineEdit_32)
        self.label_36 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.formLayout_4.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_36)
        self.lineEdit_33 = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_33.setReadOnly(True)
        self.lineEdit_33.setObjectName(_fromUtf8("lineEdit_33"))
        self.formLayout_4.setWidget(10, QtGui.QFormLayout.FieldRole, self.lineEdit_33)
        self.label_37 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.formLayout_4.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_37)
        self.lineEdit_34 = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_34.setReadOnly(True)
        self.lineEdit_34.setObjectName(_fromUtf8("lineEdit_34"))
        self.formLayout_4.setWidget(11, QtGui.QFormLayout.FieldRole, self.lineEdit_34)
        self.label_38 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.formLayout_4.setWidget(12, QtGui.QFormLayout.LabelRole, self.label_38)
        self.lineEdit_35 = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_35.setReadOnly(True)
        self.lineEdit_35.setObjectName(_fromUtf8("lineEdit_35"))
        self.formLayout_4.setWidget(12, QtGui.QFormLayout.FieldRole, self.lineEdit_35)
        self.label_39 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.formLayout_4.setWidget(13, QtGui.QFormLayout.LabelRole, self.label_39)
        self.lineEdit_36 = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_36.setReadOnly(True)
        self.lineEdit_36.setObjectName(_fromUtf8("lineEdit_36"))
        self.formLayout_4.setWidget(13, QtGui.QFormLayout.FieldRole, self.lineEdit_36)
        self.label_40 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.formLayout_4.setWidget(14, QtGui.QFormLayout.LabelRole, self.label_40)
        self.lineEdit_37 = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_37.setReadOnly(True)
        self.lineEdit_37.setObjectName(_fromUtf8("lineEdit_37"))
        self.formLayout_4.setWidget(14, QtGui.QFormLayout.FieldRole, self.lineEdit_37)
        self.label_41 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.formLayout_4.setWidget(15, QtGui.QFormLayout.LabelRole, self.label_41)
        self.lineEdit_38 = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_38.setReadOnly(True)
        self.lineEdit_38.setObjectName(_fromUtf8("lineEdit_38"))
        self.formLayout_4.setWidget(15, QtGui.QFormLayout.FieldRole, self.lineEdit_38)
        self.label_42 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.formLayout_4.setWidget(16, QtGui.QFormLayout.LabelRole, self.label_42)
        self.lineEdit_39 = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_39.setReadOnly(True)
        self.lineEdit_39.setObjectName(_fromUtf8("lineEdit_39"))
        self.formLayout_4.setWidget(16, QtGui.QFormLayout.FieldRole, self.lineEdit_39)
        self.label_43 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.formLayout_4.setWidget(17, QtGui.QFormLayout.LabelRole, self.label_43)
        self.lineEdit_40 = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_40.setReadOnly(True)
        self.lineEdit_40.setObjectName(_fromUtf8("lineEdit_40"))
        self.formLayout_4.setWidget(17, QtGui.QFormLayout.FieldRole, self.lineEdit_40)
        self.verticalLayout_3.addLayout(self.formLayout_4)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_4.addWidget(self.scrollArea_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.amounts, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 755, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpenFile = QtGui.QAction(MainWindow)
        self.actionOpenFile.setObjectName(_fromUtf8("actionOpenFile"))
        self.actionAddFile = QtGui.QAction(MainWindow)
        self.actionAddFile.setObjectName(_fromUtf8("actionAddFile"))
        self.actionAbout_AnaText = QtGui.QAction(MainWindow)
        self.actionAbout_AnaText.setObjectName(_fromUtf8("actionAbout_AnaText"))
        self.Documentation = QtGui.QAction(MainWindow)
        self.Documentation.setWhatsThis(_fromUtf8(""))
        self.Documentation.setObjectName(_fromUtf8("Documentation"))
        self.actionCompany_related_terms = QtGui.QAction(MainWindow)
        self.actionCompany_related_terms.setObjectName(_fromUtf8("actionCompany_related_terms"))
        self.actionSurnames = QtGui.QAction(MainWindow)
        self.actionSurnames.setObjectName(_fromUtf8("actionSurnames"))
        self.actionJunk_keywords = QtGui.QAction(MainWindow)
        self.actionJunk_keywords.setObjectName(_fromUtf8("actionJunk_keywords"))
        self.actionOther_mis_spelled_words = QtGui.QAction(MainWindow)
        self.actionOther_mis_spelled_words.setObjectName(_fromUtf8("actionOther_mis_spelled_words"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionColumn_Data = QtGui.QAction(MainWindow)
        self.actionColumn_Data.setObjectName(_fromUtf8("actionColumn_Data"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setWhatsThis(_fromUtf8(""))
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionCompany_related_terms_2 = QtGui.QAction(MainWindow)
        self.actionCompany_related_terms_2.setObjectName(_fromUtf8("actionCompany_related_terms_2"))
        self.actionSurnames_2 = QtGui.QAction(MainWindow)
        self.actionSurnames_2.setObjectName(_fromUtf8("actionSurnames_2"))
        self.actionOther_miss_spelled_words = QtGui.QAction(MainWindow)
        self.actionOther_miss_spelled_words.setObjectName(_fromUtf8("actionOther_miss_spelled_words"))
        self.actionJunk_keywords_2 = QtGui.QAction(MainWindow)
        self.actionJunk_keywords_2.setObjectName(_fromUtf8("actionJunk_keywords_2"))
        self.actionAdd_Sheet_name = QtGui.QAction(MainWindow)
        self.actionAdd_Sheet_name.setObjectName(_fromUtf8("actionAdd_Sheet_name"))
        self.AddSettings = QtGui.QAction(MainWindow)
        self.AddSettings.setObjectName(_fromUtf8("AddSettings"))
        self.menuFile.addAction(self.actionOpenFile)
        self.menuFile.addAction(self.actionAddFile)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuTools.addAction(self.AddSettings)
        self.menuHelp.addAction(self.Documentation)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_AnaText)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.elapsed_time.setText(_translate("MainWindow", "Time Elapsed: ", None))
        self.timeEdit.setDisplayFormat(_translate("MainWindow", "hh:mm:ss", None))
        self.start_button.setText(_translate("MainWindow", "Start", None))
        self.cancel_button.setText(_translate("MainWindow", "Cancel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Page", None))
        self.label_4.setText(_translate("MainWindow", "Total Credit:", None))
        self.label_6.setText(_translate("MainWindow", "Total Debit:", None))
        self.label_2.setText(_translate("MainWindow", "Total Lines:", None))
        self.label_5.setText(_translate("MainWindow", "Credit Mapped:", None))
        self.label_7.setText(_translate("MainWindow", "Debit Mapped:", None))
        self.label_3.setText(_translate("MainWindow", "Lines Mapped:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.summary), _translate("MainWindow", "Summary", None))
        self.label_8.setText(_translate("MainWindow", "Debit:", None))
        self.label_9.setText(_translate("MainWindow", "Cash:", None))
        self.label_10.setText(_translate("MainWindow", "ATM:", None))
        self.label_12.setText(_translate("MainWindow", "ATM Reversal:", None))
        self.label_13.setText(_translate("MainWindow", "Salary:", None))
        self.label_11.setText(_translate("MainWindow", "Interconnected:", None))
        self.label_14.setText(_translate("MainWindow", "Cheque:", None))
        self.label_17.setText(_translate("MainWindow", "Clearing:", None))
        self.label_16.setText(_translate("MainWindow", "NEFT:", None))
        self.label_15.setText(_translate("MainWindow", "RTGS:", None))
        self.label_18.setText(_translate("MainWindow", "Reject:", None))
        self.label_19.setText(_translate("MainWindow", "Reversal:", None))
        self.label_20.setText(_translate("MainWindow", "Tax:", None))
        self.label_23.setText(_translate("MainWindow", "Charges:", None))
        self.label_22.setText(_translate("MainWindow", "Transfer:", None))
        self.label_21.setText(_translate("MainWindow", "TDS:", None))
        self.label_24.setText(_translate("MainWindow", "Loan:", None))
        self.label_28.setText(_translate("MainWindow", "Investment:", None))
        self.label_25.setText(_translate("MainWindow", "Credit:", None))
        self.label_26.setText(_translate("MainWindow", "Cash:", None))
        self.label_27.setText(_translate("MainWindow", "ATM:", None))
        self.label_29.setText(_translate("MainWindow", "ATM Reversal:", None))
        self.label_30.setText(_translate("MainWindow", "Salary:", None))
        self.label_31.setText(_translate("MainWindow", "Interconnected:", None))
        self.label_32.setText(_translate("MainWindow", "Cheque:", None))
        self.label_33.setText(_translate("MainWindow", "Clearing:", None))
        self.label_34.setText(_translate("MainWindow", "NEFT:", None))
        self.label_35.setText(_translate("MainWindow", "RTGS:", None))
        self.label_36.setText(_translate("MainWindow", "Reject:", None))
        self.label_37.setText(_translate("MainWindow", "Reversal:", None))
        self.label_38.setText(_translate("MainWindow", "Tax:", None))
        self.label_39.setText(_translate("MainWindow", "Charges:", None))
        self.label_40.setText(_translate("MainWindow", "Transfer:", None))
        self.label_41.setText(_translate("MainWindow", "TDS:", None))
        self.label_42.setText(_translate("MainWindow", "Loan:", None))
        self.label_43.setText(_translate("MainWindow", "Investment:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.amounts), _translate("MainWindow", "Amounts", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menuTools.setTitle(_translate("MainWindow", "&Tools", None))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help", None))
        self.actionOpenFile.setText(_translate("MainWindow", "&Open", None))
        self.actionOpenFile.setStatusTip(_translate("MainWindow", "Open Excel files", None))
        self.actionOpenFile.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionAddFile.setText(_translate("MainWindow", "Add", None))
        self.actionAddFile.setShortcut(_translate("MainWindow", "Ctrl++", None))
        self.actionAbout_AnaText.setText(_translate("MainWindow", "About AnaText", None))
        self.actionAbout_AnaText.setStatusTip(_translate("MainWindow", "About AnaText", None))
        self.Documentation.setText(_translate("MainWindow", "Documantation", None))
        self.Documentation.setToolTip(_translate("MainWindow", "Documantation", None))
        self.Documentation.setStatusTip(_translate("MainWindow", "Documantation", None))
        self.Documentation.setShortcut(_translate("MainWindow", "Ctrl+?", None))
        self.actionCompany_related_terms.setText(_translate("MainWindow", "Add company related terms", None))
        self.actionSurnames.setText(_translate("MainWindow", "Add surnames", None))
        self.actionJunk_keywords.setText(_translate("MainWindow", "Add junk keywords", None))
        self.actionOther_mis_spelled_words.setText(_translate("MainWindow", "Add other miss-spelled words", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences", None))
        self.actionColumn_Data.setText(_translate("MainWindow", "&Column Data", None))
        self.actionExit.setText(_translate("MainWindow", "&Exit", None))
        self.actionExit.setStatusTip(_translate("MainWindow", "Exit", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionCompany_related_terms_2.setText(_translate("MainWindow", "Company related terms", None))
        self.actionSurnames_2.setText(_translate("MainWindow", "Surnames", None))
        self.actionOther_miss_spelled_words.setText(_translate("MainWindow", "Other miss-spelled words", None))
        self.actionJunk_keywords_2.setText(_translate("MainWindow", "Junk keywords", None))
        self.actionAdd_Sheet_name.setText(_translate("MainWindow", "Add sheet name", None))
        self.AddSettings.setText(_translate("MainWindow", "Add Keywords", None))

