# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'extras/main_window.ui'
#
# Created: Mon Jul 14 22:49:49 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(755, 563)
        MainWindow.setMaximumSize(QtCore.QSize(766, 586))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.start_button = QtGui.QPushButton(self.centralwidget)
        self.start_button.setObjectName(_fromUtf8("start_button"))
        self.horizontalLayout_2.addWidget(self.start_button)
        self.cancel_button = QtGui.QPushButton(self.centralwidget)
        self.cancel_button.setObjectName(_fromUtf8("cancel_button"))
        self.horizontalLayout_2.addWidget(self.cancel_button)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 755, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpenFile = QtGui.QAction(MainWindow)
        self.actionOpenFile.setObjectName(_fromUtf8("actionOpenFile"))
        self.actionAddFile = QtGui.QAction(MainWindow)
        self.actionAddFile.setObjectName(_fromUtf8("actionAddFile"))
        self.actionAbout_AnaText = QtGui.QAction(MainWindow)
        self.actionAbout_AnaText.setObjectName(_fromUtf8("actionAbout_AnaText"))
        self.Documentation = QtGui.QAction(MainWindow)
        self.Documentation.setWhatsThis(_fromUtf8(""))
        self.Documentation.setObjectName(_fromUtf8("Documentation"))
        self.actionCompany_related_terms = QtGui.QAction(MainWindow)
        self.actionCompany_related_terms.setObjectName(_fromUtf8("actionCompany_related_terms"))
        self.actionSurnames = QtGui.QAction(MainWindow)
        self.actionSurnames.setObjectName(_fromUtf8("actionSurnames"))
        self.actionJunk_keywords = QtGui.QAction(MainWindow)
        self.actionJunk_keywords.setObjectName(_fromUtf8("actionJunk_keywords"))
        self.actionOther_mis_spelled_words = QtGui.QAction(MainWindow)
        self.actionOther_mis_spelled_words.setObjectName(_fromUtf8("actionOther_mis_spelled_words"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionColumn_Data = QtGui.QAction(MainWindow)
        self.actionColumn_Data.setObjectName(_fromUtf8("actionColumn_Data"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setWhatsThis(_fromUtf8(""))
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionCompany_related_terms_2 = QtGui.QAction(MainWindow)
        self.actionCompany_related_terms_2.setObjectName(_fromUtf8("actionCompany_related_terms_2"))
        self.actionSurnames_2 = QtGui.QAction(MainWindow)
        self.actionSurnames_2.setObjectName(_fromUtf8("actionSurnames_2"))
        self.actionOther_miss_spelled_words = QtGui.QAction(MainWindow)
        self.actionOther_miss_spelled_words.setObjectName(_fromUtf8("actionOther_miss_spelled_words"))
        self.actionJunk_keywords_2 = QtGui.QAction(MainWindow)
        self.actionJunk_keywords_2.setObjectName(_fromUtf8("actionJunk_keywords_2"))
        self.actionAdd_Sheet_name = QtGui.QAction(MainWindow)
        self.actionAdd_Sheet_name.setObjectName(_fromUtf8("actionAdd_Sheet_name"))
        self.AddSettings = QtGui.QAction(MainWindow)
        self.AddSettings.setObjectName(_fromUtf8("AddSettings"))
        self.menuFile.addAction(self.actionOpenFile)
        self.menuFile.addAction(self.actionAddFile)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuTools.addAction(self.AddSettings)
        self.menuHelp.addAction(self.Documentation)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_AnaText)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.start_button.setText(_translate("MainWindow", "Start", None))
        self.cancel_button.setText(_translate("MainWindow", "Cancel", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menuTools.setTitle(_translate("MainWindow", "&Tools", None))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help", None))
        self.actionOpenFile.setText(_translate("MainWindow", "&Open", None))
        self.actionOpenFile.setStatusTip(_translate("MainWindow", "Open Excel files", None))
        self.actionOpenFile.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionAddFile.setText(_translate("MainWindow", "Add", None))
        self.actionAddFile.setShortcut(_translate("MainWindow", "Ctrl++", None))
        self.actionAbout_AnaText.setText(_translate("MainWindow", "About AnaText", None))
        self.actionAbout_AnaText.setStatusTip(_translate("MainWindow", "About AnaText", None))
        self.Documentation.setText(_translate("MainWindow", "Documantation", None))
        self.Documentation.setToolTip(_translate("MainWindow", "Documantation", None))
        self.Documentation.setStatusTip(_translate("MainWindow", "Documantation", None))
        self.Documentation.setShortcut(_translate("MainWindow", "Ctrl+?", None))
        self.actionCompany_related_terms.setText(_translate("MainWindow", "Add company related terms", None))
        self.actionSurnames.setText(_translate("MainWindow", "Add surnames", None))
        self.actionJunk_keywords.setText(_translate("MainWindow", "Add junk keywords", None))
        self.actionOther_mis_spelled_words.setText(_translate("MainWindow", "Add other miss-spelled words", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences", None))
        self.actionColumn_Data.setText(_translate("MainWindow", "&Column Data", None))
        self.actionExit.setText(_translate("MainWindow", "&Exit", None))
        self.actionExit.setStatusTip(_translate("MainWindow", "Exit", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionCompany_related_terms_2.setText(_translate("MainWindow", "Company related terms", None))
        self.actionSurnames_2.setText(_translate("MainWindow", "Surnames", None))
        self.actionOther_miss_spelled_words.setText(_translate("MainWindow", "Other miss-spelled words", None))
        self.actionJunk_keywords_2.setText(_translate("MainWindow", "Junk keywords", None))
        self.actionAdd_Sheet_name.setText(_translate("MainWindow", "Add sheet name", None))
        self.AddSettings.setText(_translate("MainWindow", "Add Keywords", None))

